version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: customers
      - name: geolocation
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: orders
      - name: products
      - name: sellers
      - name: product_category_translation

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: customer_unique_id
        tests: [not_null]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: customer_id

  - name: stg_order_items
    columns:
      - name: order_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_orders')
                field: order_id
      - name: product_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_products')
                field: product_id

  - name: dim_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: fct_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_customers')
                field: customer_id

  - name: fct_payments
    columns:
      - name: order_id
        tests:
          - relationships:
              arguments:
                to: ref('fct_orders')
                field: order_id

  - name: kpi_monthly_sales
    columns:
      - name: month
        tests: [not_null, unique]
