olist_ai_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'olist') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'olist') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'olist') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
